### ISSUE TITLE
Create docker-compose configuration for the supervisor

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-supervisor#1687]
Newer versions of the supervisor will receive the configuration supervisor service on the target state. Right now that configuration is balena's default configuration (see below). We need to create a proper configuration for the supervisor service so it can eventually update and create its own container

```
version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  main:
    image: 'balena/amd64-supervisor:v12.5.10'
    privileged: true
    tty: true
    restart: always
    network_mode: host
    volumes:
      - 'resin-data:/data'
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'
```
