### ISSUE TITLE
New target state prevented from being applied, when network without both subnet and gateway created

### ISSUE THREAD

**Issue by anujdeshpande** [balena-os/balena-supervisor#1693]

**Comment by pipex** [comment]
Here is the replication

Create the following docker-compose and perform a push in local mode. You'll get a looping exception with the message "Network IPAM config entries must have both a subnet and gateway", and will not be able to push a correct target state after that.

```
version: '2.1'

services:
  hello:
    build: ./hello-world
    networks:
      my_net:
        ipv4_address: 172.16.238.10

networks:
  my_net:
    driver: bridge
    ipam:
      driver: default
      config: 
        - gateway: 172.16.238.1
```
