### ISSUE TITLE
Create `$APPUUID_default` networks as config-only when not needed to not conflict with host addressing

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#2062]
A `$APPUUID_default` network is created with default networking for the user application, unless configured explicitly with:
```
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ...
          gateway: ...
```
in the fleet's docker-compose. 

v13+ Supervisors move in the direction of the user-app model, so a `$SUPERVISOR-APP-UUID_default` network is created in the same way. However, because no `ipam` configs are specified, the address space of this network may collide with user networks.

Solution: as network_mode for the Supervisor app is `host`, the network can still be created for purposes of determining whether target state has been applied, but only as a config, with the `ConfigOnly` create option. The network will still be available in the Engine to query, but no networks will actually be set up in host. This change will apply for any app where all services have `network_mode: host` specified.
