### ISSUE TITLE
A service which depends on a oneshot does not get started

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#2409]
Supervisor 16.12.8.

Reproduction:
```
version: '2.4'

services:
  parent-oneshot:
    image: alpine
    command: sh -c 'echo "Oneshot exiting" && exit 0'
    restart: no
    stop_signal: SIGKILL
  child:
    image: alpine
    command: sh -c 'echo "Child sleeping" && sleep infinity'
    stop_signal: SIGKILL
    depends_on:
      - parent-oneshot
```

In the reproduction, the child service never gets started by the Supervisor, as the Supervisor is waiting on the parent service to be running to start the child. However, the parent service starts and exits immediately. This diverges from docker-compose's behavior, where the child starts as long as the parent has started (with default short form depends_on config).
